3v-workspace/Data_converter

ratu/services.py

add services.py

---

ratu/models/ratu_models.py

Added koatuu records to:
- class Region
- class District
- class City
- class Citydistrict

Adding a column koatuu to ratu_models.py

---

data_converter/settings.py
data_converter/urls.py
ratu/admin.py
ratu/migrations/0032_auto_20200417_1531.py
ratu/models/rfop_models.py
ratu/models/ruo_models.py
ratu/serializers.py
ratu/urls.py
ratu/views.py

API structure for rfop and ruo

rfop_ruo_api

---

ratu/serializers/ratu_serializers.py
ratu/serializers/rfop_serializers.py
ratu/serializers/ruo_serializers.py
ratu/urls.py
ratu/views/ratu_views.py
ratu/views/rfop_views.py
ratu/views/ruo_views.py

changed project structure ( mkdir serializers & views )

Moving views and serializers under their own folders

---

ratu/services/koatuu_service.py

Adding values to koatuu fields of existing ratu_region table

Adding values to koatuu fields of existing ratu_region table

---

.gitignore
data_converter/settings.py
ratu/services/main.py
ratu/services/ratu_service.py
ratu/services/rfop_service.py
ratu/services/ruo_service.py
script.py
update.cfg

compare filesize, download, unzip and rename files.

New download

---

ratu/services/main.py

Function get_first_word added to main.py

Function get_first_word added to main.py

---

data_converter/pagination.py
data_converter/settings.py
data_converter/urls.py
ratu/views/ratu_views.py
ratu/views/rfop_views.py
ratu/views/ruo_views.py
ratu/views/views.py

in this pr i & Vital worked together. We add  a pagination to ruo, rfop & ratu views

Ruo rfop  pagination

---

ratu/serializers/ratu_serializers.py

add name object

---

data_ocean/services/ratu_service.py

Deleted category items in fields like ratu_city.name.

Ratu service tables to lowercase and adapting to koatuu.json

---

data_ocean/services/koatuu_service.py

This version fills all the koatuu fields for all current records.

Koatuu_service

---

data_ocean/converter.py
requirements.txt

New parser for xml data sources

New parser for xml data sources

---

.gitignore
location_register/converter/ratu.py

I find an error in ratu file, and fix it up.

Adding source_data folder to gitignire and fixing up function name in ratu converter

---

business_register/models/company_models.py
business_register/serializers/company_serializers.py

modify UO serializer with using 'related_name', and deleting excess fields

modify_serializer_uo

---

business_register/constants.py
business_register/converter/history.py

constants class

---

business_register/views/company_views.py
business_register/views/rfop_views.py

Add caching to get data from FOP & Company registers

Do 71 Add caching to get data from FOP & Company registers

---

data_converter/pagination.py
data_converter/settings.py

Do 138 add CustomPagination 

---

business_register/serializers/company_serializers.py
business_register/views/company_views.py
data_converter/urls.py

add api to historical_company

---

users/admin.py

DO-723 add_users_columns_to_admin_panel

DO-723 add_users_columns_to_admin_panel

---

business_register/serializers/company_and_pep_serializers.py
business_register/views/company_views.py
data_converter/urls.py

[DO-175] Added API for company related tables: Assignee, CompanyDetails, Founder, Signer
[DO-175]: https://dataoceanus.atlassian.net/browse/DO-175

[DO-175] Add historical company api

---

stats/views.py

Lyuba said to count the current user.

Changed user counter

---

data_ocean/converter.py

Converter.process() forms chunk with 1 more instance than chunk size

[DO-1167] Converter fix

---

payment_system/emails.py
payment_system/locale/uk/LC_MESSAGES/django.po
payment_system/middleware.py

- [DO-1174] Fix Emails translations
- fix request counter: only 5xx codes not subtract request
- fix email translations

[DO-1174] Fix Emails translations, fix request counter

---

data_ocean/utils.py

The format date function returns error if invalid input now. It should return nothing in that case.

[DO-1254] Improve format date function

---

data_ocean/utils.py

For avoid error in linux when year is less then 1000

[DO-]Fix less than 1000 year format

---

payment_system/serializers.py

Fixed
https://razom.atlassian.net/browse/DO-1153

[DO-1153]  Fix the issue with an inappropriate number of users

---

business_register/converter/company_converters/ukr_company.py
data_ocean/downloader.py

after 12.30.2020 the full UO source file from data.gov.ua needs to be decoded and replaced some symbols by this method

[DO-1310] source file fix

---

business_register/converter/company_converters/ukr_company_full.py

1. Changed the getting all companies id's way. Now it not spends memory.
2. Fixed bug with empty authority case.

[DO-1055] Refactoring & fix after test

---

business_register/filters.py

Added descriptions for query parameters. Also changed searching arguments from ID to NAME.
https://razom.atlassian.net/browse/DO-1359

DO-1359 Added description to FOP section in API

---

users/admin.py

Revert "fix after upgrade django rest framework"

---

data_ocean/management/commands/get_record.py
data_ocean/utils.py

It gets original records from source file by some search text.
It outputs like this:
```
>>> from data_ocean.utils import get_source_records
>>> get_source_records('24377784')
Converter has imported.
Record # 159651 from: 17.1-EX_XML_EDR_UO_FULL_10.01.2021.xml
-------------------------------------------------------------------------
NAME : "ЕТРЕКС-1"
SHORT_NAME : ТОВ "ЕТРЕКС-1"
OPF : ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ
EDRPOU : 24377784
ADDRESS : Україна, 02160, ПРОСПЕКТ ВОЗЗ"ЄДНАННЯ, Б.21, МІСТО КИЇВ, ДНІПРОВСЬКИЙ РАЙОН
STAN : припинено
FOUNDING_DOCUMENT_NUM : 
EXECUTIVE_POWER : 
FOUNDERS : 
FOUNDER : АКЦІОНЕРНЕ ТОВАРИСТВО "ЦІНТЕХ", Ліхтенштейн, ВУЛ. БАЛЬЦЕРС, 6FL-9490, М. ВАДУЦ, розмір внеску до статутного фонду - 100000,00 грн.
FOUNDER : ПІДПРИЄМСТВО З ІНОЗЕМНИМИ ІНВЕСТИЦІЯМИ …
```

[DO-1595] Utility for get records

---

business_register/converter/company_converters/ukr_company_full.py

converters speed increased to 24%
```
----------------------------------------------------------------------------------
update kveds                     0:03:13         32.25 %
update exchange data             0:02:07         21.28 %
update signers                   0:01:31         15.27 %
update beneficiaries             0:00:26         4.38 %
update founders                  0:00:25         4.31 %
trying get companies             0:00:25         4.19 %
update termination               0:00:24         4.01 %
update predecessors              0:00:20         3.39 %
update company details           0:00:19         3.27 %
update bancruptcy                0:00:19         3.24 %
update assignes                  0:00:15         2.52 %
getting data from record         0:00:07         1.24 % …
```

id instead object improve

---

business_register/converter/company_converters/ukr_company_full.py

When new company appears signers writed doble - fix it

remove doble signers adding

---

business_register/converter/company_converters/ukr_company_full.py

Here founders & beneficiaries update in same metod. Before founders & benef.. was updating for 10.83% + 8.72% of total time. Now only 9.88% for both.
Before:
```
----------------------------------------------------------------------------------
update kveds                     0:00:08         13.7 %
update founders                  0:00:06         10.83 %
trying get companies             0:00:05         9.58 %
update beneficiaries             0:00:05         8.72 %
update termination               0:00:05         8.58 %
update predecessors              0:00:04         8.21 %
update company details           0:00:04         7.77 %
update bancruptcy                0:00:04         7.6 %
update exchange data             0:00:04         7.51 %
update signers                   0:00:04 …
```

[DO-1604] Improve founder saving

---

business_register/views/pep_views.py
data_ocean/permissions.py

Allows access only to authenticated users with active and not default project(s).

[DO-1636] Change export permission

---

business_register/views/pep_views.py

(cherry picked from commit 01352a705ebc39aedea00105ee99eedeb9154558)

[PROD] fix pep_check documentation

---

business_register/converter/company_converters/ukr_company_full.py

remove unreadable characters in uo_full source file

[DO-1775] Urgent repair Ukr companies converter

---

business_register/converter/company_converters/ukr_company_full.py
business_register/converter/pep.py
data_ocean/converter.py
data_ocean/models.py
data_ocean/templates/data_ocean/emails/report.html

Add status for 'in progress' register updates

[DO-1687] Upgrade report for 'in progress' updates

---

business_register/converter/fop_full.py

Speed up converter by avoid request related objects:
`stored_foptokved.kved_id == kved.id` instead `stored_foptokved.kved.name == kved.name`  &
`stored_exchange_data.authority_id == authority.id if authority else None` instead `stored_exchange_data.authority == authority` &
`stored_exchange_data.taxpayer_type_id == taxpayer_type.id if taxpayer_type else None` instead `stored_exchange_data.taxpayer_type == taxpayer_type`

Speed up fop converter

---

business_register/admin.py

(cherry picked from commit 2399e27b11f64cd063294309180ef6a15b48ffb7)

[DO-1813] [PROD] Add more filters and list_display to sanctions admin panel

---

data_ocean/fixtures/register.json
data_ocean/management/commands/actualize_register.py
data_ocean/models.py

Add method for actualizing update_at & total_records data in Register model
Add relevant api for KOATUU in fixture

[DO-1668] Actualize registers updates

---

business_register/serializers/company_and_pep_serializers.py

Update company_and_pep_serializers.py
From/to relationship_type_en added to API

Display filled fields in API (from/to relationship_en)

---

business_register/models/company_models.py
business_register/models/pep_models.py
data_ocean/transliteration/utils.py

Bug with empty fields for translating

[DO-1807,1892] Fix_bug_with_eng_fields

---

data_ocean/fixtures/register.json

Add new register to register register

[DO-1957] Add person sanction to fixture

---

business_register/converter/declaration.py
business_register/models/declaration_models.py

Reverts 3v-workspace/Data_converter#855
@IegorSoboliev

Revert "[DO-1843]Storing liability" Missed migrations

---

business_register/models/pep_models.py
business_register/serializers/company_and_pep_serializers.py

[DO-1980] Transliterate place of work

---

business_register/serializers/company_and_pep_serializers.py

(cherry picked from commit 20ec6b5bfdc1f2f60981251ffcef13b85a978568)

[DO-1993] HotFix pep_type field [PROD]

---

business_register/filters.py

added filters for `fullname_en` & `last_employer_en` fields

[DO-1977; DO-1980] Add filters to pepfilterset

---

business_register/serializers/company_and_pep_serializers.py

for translating related persons names in PepDetail page on dataplatform

[DO-1639] Add fullname_en to pep short serializer'

---

business_register/pep_scoring/rules.py

0)Create BaseScoringRule class
1)Create PEP03 scoring rule

[DO - 1720] Create PEP03 scoring rule

---

business_register/filters.py
business_register/views/sanction_views.py

Added `country_of_registration_uk` filter

[DO-1906] Add_ukrainian_language_search_country_of_registration
